import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from typing import Any, List
from datetime import datetime

class ReportGenerator:
    @classmethod
    def generate_pdf_report(cls, session: Any, results: List[Any], filepath: str) -> str:
        """
        Generates a PDF test report matching OIML R76-2 structural format.
        """
        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4
        
        instrument = session.instrument
        
        # Header
        c.setFont("Helvetica-Bold", 16)
        c.drawString(1 * inch, height - 1 * inch, "CALIBRA - Standardized Test Report")
        
        c.setFont("Helvetica", 10)
        c.drawString(1 * inch, height - 1.3 * inch, f"Session ID: {session.id}")
        c.drawString(4 * inch, height - 1.3 * inch, f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}")
        
        if instrument:
            # Instrument details
            c.setFont("Helvetica-Bold", 12)
            c.drawString(1 * inch, height - 1.8 * inch, "1. Instrument Profile")
            c.setFont("Helvetica", 10)
            c.drawString(1.2 * inch, height - 2.1 * inch, f"Manufacturer: {instrument.manufacturer}")
            c.drawString(1.2 * inch, height - 2.3 * inch, f"Model: {instrument.model}")
            c.drawString(1.2 * inch, height - 2.5 * inch, f"Accuracy Class: {instrument.accuracy_class}")
            c.drawString(1.2 * inch, height - 2.7 * inch, f"Max Capacity: {instrument.max_capacity}")
            c.drawString(1.2 * inch, height - 2.9 * inch, f"Min Capacity: {instrument.min_capacity}")
            c.drawString(1.2 * inch, height - 3.1 * inch, f"Verification Interval (e): {instrument.verification_interval_e}")
        
        # Test Results
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1 * inch, height - 3.6 * inch, "2. Test Results")
        
        y = height - 4.0 * inch
        for idx, result in enumerate(results):
            if y < 1 * inch:
                c.showPage()
                y = height - 1 * inch
            
            c.setFont("Helvetica-Bold", 10)
            c.drawString(1.2 * inch, y, f"Test: {result.test_definition.name if result.test_definition else 'Unknown'}")
            
            c.setFont("Helvetica", 10)
            status_color = {"PASS": "green", "FAIL": "red", "REVIEW": "orange"}.get(result.status, "black")
            c.drawString(4 * inch, y, f"Status: {result.status}")
            
            y -= 0.2 * inch
            c.drawString(1.4 * inch, y, f"Reason: {result.decision_reason}")
            
            y -= 0.3 * inch
            
        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(1 * inch, 0.5 * inch, "Generated by CALIBRA - Explainable Metrology Compliance Engine")
        
        c.save()
        return filepath
